baseURL: https://charlieegan3.com
languageCode: en-us
title: charlieegan3
summaryLength: 25
taxonomies: {}
pygmentsCodeFences: true

params:
  twitter: "charlieegan3"
  name: Charlie Egan

outputFormats:
  SearchIndex:
    mediaType: "application/json"
    baseName: "searchindex"
    isPlainText: true
    notAlternative: true

outputs:
  home: ["HTML", "SearchIndex", "RSS"]

rssLimit: 30

menu:
  main:
  - identifier: home
    name: home
    title: homepage
    url: /
    weight: 1
  - identifier: about
    name: about
    title: read all about it
    url: /about/
    weight: 2
  - identifier: posts
    name: blog
    title: view my blog posts
    url: /posts/
    weight: 2
  - identifier: weeknotes
    name: weeknotes
    title: view my weekly notes
    url: /weeknotes/
    weight: 2
