kind: pipeline
name: nginx

platform:
  # make reference to arm sha
  arch: amd64

steps:
- name: set-tags
  image: busybox
  commands:
  - echo -n "$DRONE_COMMIT" > .tags
- name: deploy
  image: plugins/docker
  settings:
    repo: charlieegan3/photos-rebuilder
    username: charlieegan3
    password:
      from_secret: DOCKER_PASSWORD
    dockerfile: Dockerfile.arm
