runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^((?!www).)*$

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html
  secure: always
  http_headers:
    Vary: User-Agent

- url: /(blog|articles|til)/?
  static_files: www/\1/index.html
  upload: www/(blog|articles|til)/index.html
  secure: always
  http_headers:
    Vary: User-Agent

- url: /(.*\.html)
  static_files: www/\1
  upload: www/(.*)
  secure: always
  http_headers:
    Vary: User-Agent

- url: /(.*\.(js|css|jpg|png|gif|ico))$
  static_files: www/\1
  upload: www/.*\.(js|css|jpg|png|gif|ico)$
  secure: always
  http_headers:
    Vary: User-Agent
  expiration: 10d

- url: /(feed|rss).*
  static_files: www/blog/feed.rss
  upload: www/blog/feed.rss
  secure: always

error_handlers:
  - file: www/error.html
