runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^((?!www).)*$

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html
  secure: always
  http_headers:
    Vary: Accept-Encoding

- url: /(\w+)/?
  static_files: www/\1/index.html
  upload: www/(\w+)/index.html
  secure: always
  http_headers:
    Vary: Accept-Encoding

- url: /(.*\.html)
  static_files: www/\1
  upload: www/(.*)
  secure: always
  http_headers:
    Vary: Accept-Encoding

- url: /(.*\.(js|css|jpg|png|gif|ico|ttf|woff|woff2|svg))$
  static_files: www/\1
  upload: www/.*\.(js|css|jpg|png|gif|ico|ttf|woff|woff2|svg)$
  secure: always
  http_headers:
    Vary: Accept-Encoding
  expiration: 10d

- url: /(.*\.(json|pdf|csv|zip|txt|xml))$
  static_files: www/\1
  upload: www/.*\.(json|pdf|csv|zip|txt|xml)$
  secure: always
  http_headers:
    Vary: Accept-Encoding
  expiration: 10m

- url: /(feed|rss).*
  static_files: www/feed.rss
  upload: www/feed.rss
  secure: always

- url: /sitemap.*
  static_files: www/sitemap.xml
  upload: www/sitemap.xml
  secure: always

error_handlers:
  - file: www/error.html
