runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^((?!www).)*$

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html
  secure: always

- url: /blog
  static_files: www/blog/index.html
  upload: www/blog/index.html
  secure: always

- url: /articles
  static_files: www/articles/index.html
  upload: www/articles/index.html
  secure: always

- url: /til
  static_files: www/til/index.html
  upload: www/til/index.html
  secure: always

- url: /feed.rss
  static_files: www/blog/feed.rss
  upload: www/blog/feed.rss
  secure: always

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
  secure: always
