version: 0.2

phases:
  install:
    commands:
      - chmod +x bin/*
      - bin/bundle
  build:
    commands:
      - bin/build
  post_build:
    commands:
      - bin/deploy
      - bin/invalidations
