version: 0.2

phases:
  install:
    commands:
      - chmod +x bin/codepipeline/*
      - bin/codepipeline/bundle
  build:
    commands:
      - bin/codepipeline/build
  post_build:
    commands:
      - bin/codepipeline/deploy
      - bin/codepipeline/invalidations
      - bin/codepipeline/cleanup
