name: build-site

on:
  push:
    branches: [ master ]
  workflow_run:
    workflows: ["refresh-notion-data"]
    branches: [master]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install imagemagick
      run: |
        # needed to resize images
        sudo apt install imagemagick
    - name: Build and push
      run: |
        git fetch --unshallow origin
        ./bin/compress_images.sh
        ruby ./bin/build_site.rb
