name: refresh-notion-data

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "*/10 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Refresh and commit data
      env:
        NOTION_COOKIE: ${{ secrets.NOTION_COOKIE }}
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

        ./bin/check_notion.rb && \
        ./bin/export_notion.rb && \
        ./bin/import_notion.rb && \
        ./bin/commit.rb
